Set up DEV/PRD workflow
tnc-br/ddf-insights-analytics pull request #18
Opened 2023-09-15 22:13 UTC by kazob1998

2023-09-15 22:17 UTC, benwulfe requested changes
This is great!

For the flexible field change -- change you please describe in the PR what you added and how you tested?

2023-09-15 22:22 UTC, kazob1998 commented
tested manually with cloud function

2023-09-15 22:28 UTC, benwulfe approved these changes
:)
we need to work a little on reproducible tests (even manual ones).
lets get it in.  nice work!

2023-09-16 02:34 UTC, benwulfe approved these changes

2023-09-18 15:33 UTC, merged