Add mapbiomas alerts code
tnc-br/ddf-insights-analytics pull request #9
Opened 2023-09-07 12:56 UTC by jjcastro

2023-09-08 11:38 UTC, benwulfe requested changes
Please add a test that double checks that our expected contract with mapbiomas remains intact. 
Also please ensure its resilient to failure -- especially important given this is an external entity.

2023-09-08 11:38 UTC, benwulfe commented on fetch_mapbiomas_alerts.py
> +def fetch_alerts(lat: float, lon: float):
doccomment

2023-09-13 13:35 UTC, jjcastro commented
Done, created a test to test the contracts and added documentation

2023-09-13 15:54 UTC, benwulfe approved these changes
This is excellent. Fronza was looking for how to do this, so if you can come to next tuesday session, we can review this and the frontend code with him.

2023-09-14 14:21 UTC, merged